---
title: "Home"
date: last-modified
date-format: iso
published-title: "Last updated"
author: 
  - Pacific Islands Fisheries Science Center
engine: knitr
execute:
    eval: false
    echo: false
    output: false
title-block-banner: "#C6E6F0"
title-block-banner-color: "#001743"
html:
    embed-resources: true
    toc: true
    toc-location: right
    number-sections: true
    code-overflow: wrap
    theme: [default, customizations/custom.scss]
css: customizations/styles-home.css  
---

This repository contains code and data required to render summary documents (in both `.html` and `.pdf` formats) of South Pacific albacore (SPA) catch within the Western and Central Pacific Fisheries Commission ([WCPFC](https://www.wcpfc.int/)) convention area. Catch summaries are provided for all participating Members, Participating Territories and Cooperating Non-Members (CCMs) with longline and troll catch of SPA per the most recent [WCPFC Yearbook data](https://www.wcpfc.int/statistical-bulletins). Catch summaries are placed in the context of a proposed Conservation and Management Measure (CMM) on a management procedure (MP) for SPA ([public proposal](https://meetings.wcpfc.int/node/24363)).

Note that the data set used, [`YB_data_2023/XLS_SouthWCPFC.csv`](https://www.wcpfc.int/doc/annual-catch-estimates-2022-data-files), is the 2023 version of the [WCPFC Tuna Fishery Yearbook - Annual Catch Estimates](https://www.wcpfc.int/statistical-bulletins). The file `YB_data_2023/spa-ll-eez.csv` contains data transcribed from [SC20-SA-IP-07](https://meetings.wcpfc.int/node/23046) Table 6, and the file `YB_data_2023/ccm-dat.csv` containing CCM abbreviations was created for this repository.

[The SPA data summary can be found [here](https://n-ducharmebarth-noaa.github.io/2024-spa-summary/wcpfc-ca-spa-catch-summary.html).]{.blue}

## Github Disclaimer

This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All NOAA GitHub project code is provided on an ‘as is’ basis and the user assumes responsibility for its use. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.
